name: "Data Check"
description: "Checks data quality"
author: "Base dos Dados"
runs:
  using: composite
  steps:
    - run: pip install basedosdados==1.5.2 pytest toml
      shell: bash
    - run: cd ${{ github.workspace }}/.github/workflows/data-check/ && pytest test_data.py
      shell: bash