
# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_me_caged

table_id: microdados_movimentacao_excluida

# Título da tabela.
title: Microdados Movimentação Excluída

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: Contém dados de movimentações excluídas com competência de declaração.

# As máximas unidades espaciais que a tabela cobre.
# Exemplo:
#    - sa.br
#  
#    - sa.br.sp
#  
#    - world
spatial_coverage:
    - sa.br

# Anos cobertos pela tabela.
# Exemplos:
#     - 1995(1)2019
# Caso a cobertura não seja contínua:
#     - 2002(2)2010
#     - 2016
#     - 2020
temporal_coverage:
    - 2020-04(1)2023-02

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency: month

# Nível de observação da tabela: o que representa cada linha.
# A combinação das colunas aqui deve construir uma chave única da tabelaOpções de entity em 'https://basedosdados.org/api/3/action/bd_available_options'
# Caso a entidade seja espacial incluir a informação de 'country' Exemplos:
#     - entity: year
#       columns:
#           - ano
#     - country: br
#       entity: state
#       columns:
#           - sigla_uf
observation_level:
    - country: br
      entity: state
      columns:
          - sigla_uf
    - country: br
      entity: municipality
      columns:
          - id_municipio
          - id_municipio_6
    - entity: year
      columns:
          - ano
    - entity: month
      columns:
          - mes

last_updated:
    metadata: '2023-03-10'
    data: '2023-03-10 12:00:00'
    release:

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplos: v1.0, v1.1.3
version: v1.2

# Quem está preenchendo esses metadados?
published_by:
    name: Arthur Gusmão
    email: arthur.gusmao@basedosdados.org
    github_user: arthurfg
    ckan_user: arthurfg
    website:

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Lucas Rodrigues Cavalcanti
    email: lucas.rodrigues@basedosdados.org
    github_user: lucascr91
    ckan_user:
    website:

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: 1. Acessar o FTP do Ministério do Trabalho e Previdência; 2. Baixar os arquivos brutos no formato '.7z'; 3. Renomear as colunas para o padrão definido no Manual de Estilo; 4. Remover as colunas "competenciamov", "sigla_uf", "regiao","competenciadec", "unidadesalariocodigo" e "valorsalariofixo"; 5. Salvar os arquivos nas diretórios particionadas no formato `/caged/output/ano=AAAA/mes=MM/sigla_uf=XX/`

# Url do código de limpeza dos dados do github.
data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_me_caged/code

# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name:
    organization_id:

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:
    - ano
    - mes
    - sigla_uf

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: ano
      bigquery_type: int64
      description: Ano
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit: year
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: true
    - name: mes
      bigquery_type: int64
      description: Mês
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: mes
          column_name: mes
      measurement_unit: month
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: true
    - name: sigla_uf
      bigquery_type: string
      description: Sigla da Unidade da Federação
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: uf
          column_name: sigla
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: true
    - name: id_municipio
      bigquery_type: string
      description: ID Município - IBGE 7 Dígitos
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: municipio
          column_name: id_municipio
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: cnae_2_secao
      bigquery_type: string
      description: Classificação Nacional de Atividades Econômicas (CNAE 2.0 - Seção)
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: cnae_2
          column_name: secao
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: cnae_2_subclasse
      bigquery_type: string
      description: Subclasse do Código Nacional de Atividades Econômicas 2.0
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: saldo_movimentacao
      bigquery_type: int64
      description: Saldo de movimentação
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: cbo_2002
      bigquery_type: string
      description: Classificação Brasileira de Ocupações (CBO) - 2002
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: cbo_2002
          column_name: cbo_2002
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false      
    - name: categoria
      bigquery_type: string
      description: Categoria de trabalhador
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: grau_instrucao
      bigquery_type: string
      description: Grau de instrução ou escolaridade
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: idade
      bigquery_type: int64
      description: Idade do trabalhador
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: year
      has_sensitive_data: no
      observations: Quando acumulada representa a soma das idades
      is_in_staging: true
      is_partition: false
    - name: horas_contratuais
      bigquery_type: int64
      description: Horas contratuais
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: hour
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: raca_cor
      bigquery_type: string
      description: Raça ou Cor do Trabalhador
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: sexo
      bigquery_type: string
      description: Sexo
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: tipo_empregador
      bigquery_type: string
      description: Tipo de empregador
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: tipo_estabelecimento
      bigquery_type: string
      description: Tipo de estabelecimento
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: tipo_movimentacao
      bigquery_type: string
      description: Tipo de movimentação
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: tipo_deficiencia
      bigquery_type: string
      description: Tipo de deficiência/Beneficiário habilitado
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: indicador_trabalho_intermitente
      bigquery_type: string
      description: Indicador de trabalhador intermitente
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: indicador_trabalho_parcial
      bigquery_type: string
      description: Indicador de movimentação referente a contrato parcial
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false      
    - name: salario_mensal
      bigquery_type: float64
      description: Salário mensal em moeda corrente
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: tamanho_estabelecimento_janeiro
      bigquery_type: string
      description: Faixa de tamanho do estabelecimento em relação ao total de vínculos
          no início do ano
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: indicador_aprendiz
      bigquery_type: string
      description: Indicador de trabalhador aprendiz
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: origem_informacao
      bigquery_type: string
      description: Origem da Informação
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: indicador_fora_prazo
      bigquery_type: int64
      description: Indicador fora do prazo
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false

number_rows: 280932

metadata_modified: '2023-04-11T23:58:51.851066'
