dataset_id: br_me_rais

table_id: microdados_estabelecimentos

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: "Microdados de estabelecimentos da RAIS.\n"   

# A máxima unidade espacial que a tabela cobre.
spatial_coverage: bra

# Anos cobertos pela tabela.
temporal_coverage:
    - 1985
    - 1986
    - 1987
    - 1988
    - 1989
    - 1990
    - 1991
    - 1992
    - 1993
    - 1994
    - 1995
    - 1996
    - 1997
    - 1998
    - 1999
    - 2000
    - 2001
    - 2002
    - 2003
    - 2004
    - 2005
    - 2006
    - 2007
    - 2008
    - 2009
    - 2010
    - 2011
    - 2012
    - 2013
    - 2014
    - 2015
    - 2016
    - 2017
    - 2018
    - 2019

# A unidade temporal com qual a tabela é atualizada.
update_frequency: one_year

# Entidade representada por cada linha.
entity: []

# A unidade temporal representada por cada linha.
time_unit:

# O conjunto mínimo de colunas identificando cada linha unicamente.
# Preencha com os nomes de colunas. Ex: id_municipio, ano.
# Pode ser vazio pois certas tabelas não possuem identificadores.
identifying_columns:

last_updated:
    metadata:
    data:
    release:

version: v1.1

# Quem está preenchendo esses metadados?
published_by:
    name: Ricardo Dahis
    email: rdahis@basedosdados.org
    github_user: rdahis
    website: www.ricardodahis.com
    ckan_user: rdahis

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Ricardo Dahis
    email: rdahis@basedosdados.org
    github_user: rdahis
    ckan_user: rdahis
    website: www.ricardodahis.com
    code_url: https://github.com/basedosdados/mais/tree/master/bases/br_me_rais/code

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: "- Unificamos todos os anos.\n
    - Padronizamos nomes de variáveis.\n
    - Limpamos valores errados de células.\n
    - Renomeamos municípios nulos para 'NA'."

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

covered_by_dictionary: yes

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions: ano, sigla_uf, id_municipio

bdm_file_size:

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: ano
      bigquery_type: int64
      description: Ano
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit: year
      has_sensitive_data: no
      is_in_staging: true
      is_partition: true
    - name: sigla_uf
      bigquery_type: string
      description: Sigla da Unidade da Federação
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: uf
          column_name: sigla_uf
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: true
    - name: id_municipio
      bigquery_type: string
      description: ID Município - IBGE 7 Dígitos
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: municipio
          column_name: id_municipio
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: true
    - name: quantidade_vinculos_ativos
      bigquery_type: int64
      description: Estoque de vínculos ativos em 31/12 (quando acumulada representa
          a soma dos vinculos ativos).
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: quantidade_vinculos_clt
      bigquery_type: int64
      description: Estoque de vínculos, sob o regime CLT e Outros, ativos em 31/12
          (quando acumulada representa a soma dos vinculos ativos).
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: quantidade_vinculos_estatutarios
      bigquery_type: int64
      description: Estoque de vínculos, sob o regime estatutário, ativos em 31/12
          (quando acumulada representa a soma dos vinculos ativos).
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: natureza_estabelecimento
      bigquery_type: string
      description: Natureza do Estabelecimento
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: natureza_juridica
      bigquery_type: string
      description: Natureza Jurídica (CONCLA/2002)
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: tamanho_estabelecimento
      bigquery_type: string
      description: Tamanho do estabelecimento - empregados ativos em 31/12.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: tipo_estabelecimento
      bigquery_type: string
      description: Tipo do Estabelecimento
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: indicador_cei_vinculado
      bigquery_type: int64
      description: Indicador de CEI vinculado.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: indicador_pat
      bigquery_type: int64
      description: Indicador de estabelecimento pertencente ao PAT.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: indicador_simples
      bigquery_type: int64
      description: Indicador de optante pelo SIMPLES.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: indicador_rais_negativa
      bigquery_type: int64
      description: Indicador de Rais Negativa.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: indicador_atividade_ano
      bigquery_type: int64
      description: Indicador de estabelecimento/entidade que exerceu atividade durante
          o ano de referência.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: cnae_1
      bigquery_type: string
      description: Código Nacional de Atividades Econômicas 1.0
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: cnae_1
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: cnae_2
      bigquery_type: string
      description: Código Nacional de Atividades Econômicas 2.0
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: cnae_2
          column_name: cnae_2
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: cnae_2_subclasse
      bigquery_type: string
      description: Subclasse do Código Nacional de Atividades Econômicas 2.0
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name: 
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: subsetor_ibge
      bigquery_type: string
      description: Subsetor IBGE
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: subatividade_ibge
      bigquery_type: string
      description: Subatividade IBGE
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: cep_estabelecimento
      bigquery_type: string
      description: Código de Endereçamento Postal
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: bairros_sp
      bigquery_type: string
      description: Bairros do Municipio de São Paulo
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: distritos_sp
      bigquery_type: string
      description: Distritos do município de São Paulo
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: bairros_fortaleza
      bigquery_type: string
      description: Bairros do município de Fortaleza
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: bairros_rj
      bigquery_type: string
      description: Bairros do município do Rio de Janeiro
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: regioes_administrativas_df
      bigquery_type: string
      description: Regiões Administrativas do Distrito Federal
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
      
metadata_modified: '2021-11-04T02:37:09.014215'
