# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_geobr_mapas

table_id: mesorregiao

# Título da tabela.
title: Mesorregião

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: O geobr é um pacote R e Python que permite que os usuários acessem facilmente os shapefiles do Instituto Brasileiro de Geografia e Estatística (IBGE) e outros conjuntos oficiais de dados espaciais do Brasil. O pacote inclui uma ampla variedade de conjuntos de dados geográficos como recursos simples, disponíveis em várias escalas geográficas e por vários anos.

# As máximas unidades espaciais que a tabela cobre.
# Exemplo:
#   - sa.br
spatial_coverage:
    - sa.br

# Anos cobertos pela tabela.
# Preencher como lista de intervalos.
# Exemplos: ['1995(1)2019'], ['2002(2)2010', '2016', '2020'].
temporal_coverage:
    - 2020

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency: one_year

# Nível de observação da tabela: o que representa cada linha.
observation_level:
    - entity: region
      columns:
      - id_mesorregiao

last_updated:
    metadata: '2022-08-22'
    data: '2022-08-22 14:25:30'
    release: '2022-08-22 14:25:30'

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplo: v1.1.3
version: v1.0

# Quem está preenchendo esses metadados?
published_by:
    name: Gustavo Alcântara
    email: gustavo.alcantara@basedosdados.org
    github_user: gustavoalcantara
    ckan_user: gustavoalcantara
    website:

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Rafael H.M Pereira
    email: rafael.pereira@ipea.gov.br
    github_user: rafaelpereirabr
    ckan_user: 
    website: https://github.com/ipeaGIT/geobr

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: etl dos dados, rename e select para o Padrão da Base dos Dados.

# Url do código de limpeza dos dados.
data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_geobr_mapas/code/mesorregiao

# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name:
    organization_id:

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: id_uf
      bigquery_type: string
      description: ID da Unidade da Federação
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: uf
          column_name: id_uf
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: sigla_uf
      bigquery_type: string
      description: Sigla da Unidade da Federação
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: uf
          column_name: sigla
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true 
      is_partition: false
    - name: id_mesorregiao
      bigquery_type: string
      description: ID da Mesorregião - IBGE
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: municipio
          column_name: id_mesorregiao
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: geometria
      bigquery_type: string
      description: Polígono da Mesorregião
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false

number_rows: 137

metadata_modified: 
