# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_fbsp_absp

table_id: capital

# Título da tabela.
title: Estatísticas Criminais por Capitais e Distrito Federal

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: Trata-se de Estatísticas Criminais por capitais e Distrito Federal


# As máximas unidades espaciais que a tabela cobre.
# Exemplo:
#   - sa.br
spatial_coverage:
    - sa.br

# Anos cobertos pela tabela.
# Preencher como lista de intervalos.
# Exemplos: ['1995(1)2019'], ['2002(2)2010', '2016', '2020'].
temporal_coverage:
    - 2016(1)2021

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency: one_year

# Nível de observação da tabela: o que representa cada linha.
observation_level: 
    - entity: year
        column: ano
    - country: br
        entity: municipality
        column: id_municipio

last_updated:
    metadata: '2022-11-28'
    data: '2022-09-04 20:30:15'
    release: '2022-09-04 20:30:16'

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplo: v1.1.3
version: v1.0

# Quem está preenchendo esses metadados?
published_by:
    name: Laura amaral
    email: laura.amaral@basedosdados.org
    github_user: laura-l-amaral
    ckan_user: laura-amaral
    website: ''

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
  name: Bruno Moitinho Andrade de Souza
  email: moitinhobr@gmail.com
  github_user: https://github.com/brmoitinho
  ckan_user:
  website: https://www.linkedin.com/in/bruno-desouza/

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: Renomeei e ordenei as variáveis; exclui todas as linhas que possui NA no campo UF; retirei espaços em branco; substuí o hífen que significa que o fenômeno não existiu no dado ano na capital do estado por 0; substituí os três pontos que significam que a informação não está disponível por NAN; e uni todos os anos.

# Url do código de limpeza dos dados.
data_cleaning_code_url:  https://github.com/basedosdados/mais/tree/master/bases/br_fbsp_absp/code/microdados


# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name:
    organization_id:

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: id_municipio
      bigquery_type: int64
      description: ID Município - IBGE 7 Dígitos
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: id_municipio
          column_name: id_municipio
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: grupo
      bigquery_type: string
      description: Grupos segundo qualidade estimada dos registros estatísticos oficiais
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: sigla_uf
      bigquery_type: string
      description: Sigla da Unidade da Federação
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: uf
          column_name: sigla_uf
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: ano
      bigquery_type: int64
      description: Ano
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit: year
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_homicidio_doloso
      bigquery_type: int64
      description: 'Quantidade de Homicídios Dolosos '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_latrocinio
      bigquery_type: int64
      description: 'Quantidade de Latrocínios '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_lesao_corporal_morte
      bigquery_type: int64
      description: 'Quantidade de Lesões Corporais Seguida de Morte '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_mortes_policiais_confronto
      bigquery_type: int64
      description: 'Quantidade de Policiais Civis e Militares Mortos em Situação de
          Confronto '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_mortes_intervencao_policial
      bigquery_type: int64
      description: 'Quantidade de Mortes Decorrentes de Intervenção Policial (em serviço
          e fora de serviço) '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_mortes_intervencao_policial_civil_em_servico
      bigquery_type: int64
      description: Quantidade de Mortes decorrentes de intervenções de Policiais Civis
          em serviço
      temporal_coverage:
          - (1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_mortes_intervencao_policial_militar_em_servico
      bigquery_type: int64
      description: Quantidade de Mortes decorrentes de intervenções de Policiais Militares
          em serviço
      temporal_coverage:
          - (1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_mortes_intervencao_policial_civil_fora_de_servico
      bigquery_type: int64
      description: Quantidade de Mortes decorrentes de intervenções de Policiais Civis
          fora de serviço
      temporal_coverage:
          - (1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_mortes_intervencao_policial_militar_fora_de_servico
      bigquery_type: int64
      description: Quantidade de Mortes decorrentes de intervenções de Policiais Militares
          fora de serviço
      temporal_coverage:
          - (1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_mortes_violentas_intencionais
      bigquery_type: int64
      description: 'Quantidade de Mortes Violentas Intencionais '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_feminicidio
      bigquery_type: int64
      description: Quantidade de Vítimas de Feminicídio
      temporal_coverage:
          - 2018(1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_lesao_corporal_dolosa_violencia_domestica
      bigquery_type: int64
      description: Quantidade de Vítimas de Lesão Corporal em Violência Doméstica
      temporal_coverage:
          - 2018(1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_estupro
      bigquery_type: int64
      description: Quantidade de Vítimas por Estupro, incluindo as Vítimas de Estupro
          de Vulnerável
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_roubo_veiculos
      bigquery_type: int64
      description: Quantidade de Veículos Roubados
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_furto_veiculos
      bigquery_type: int64
      description: Quantidade de Veículos Furtados
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_roubo_furto_veiculos
      bigquery_type: int64
      description: Quantidade de Veículos Roubados e Furtados
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: proporcao_mortes_intenvencao_policial_x_mortes_violentas_intencionais
      bigquery_type: float64
      description: 'Proporção de Mortes Decorrentes de Intervenções Policiais (MDIP)
          em relação às Mortes Violentas Intencionais (MVI) '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_posse_ilegal_arma_de_fogo
      bigquery_type: int64
      description: Quantidade de Posse Ilegal de arma de fogo
      temporal_coverage:
          - 2018(1)2021
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_porte_ilegal_arma_de_fogo
      bigquery_type: int64
      description: Quantidade de Porte Ilegal de arma de fogo
      temporal_coverage:
          - 2018(1)2021
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_posse_ilegal_porte_ilegal_arma_de_fogo
      bigquery_type: int64
      description: Quantidade de Posse Ilegal e Porte Ilegal de arma de fogo
      temporal_coverage:
          - 2018(1)2021
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_trafico_entorpecente
      bigquery_type: int64
      description: Quantidade de Tráfico de Entorpecentes
      temporal_coverage:
          - 2018(1)2021
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_posse_uso_entorpecente
      bigquery_type: int64
      description: 'Quantidade de Posse e Uso de Entorpecentes        '
      temporal_coverage:
          - 2018(1)2021
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_morte_policiais_civis_confronto_em_servico
      bigquery_type: int64
      description: 'Quantidade de Policiais Civis mortos em confronto em serviço '
      temporal_coverage:
          - (1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_morte_policiais_militares_confronto_em_servico
      bigquery_type: int64
      description: Quantidade de Policiais Militares mortos em confronto em serviço
      temporal_coverage:
          - (1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_morte_policiais_civis_fora_de_servico
      bigquery_type: int64
      description: Quantidade de Policiais Civis mortos em confronto ou por lesão
          não natural fora de serviço
      temporal_coverage:
          - (1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: quantidade_morte_policiais_militares_fora_de_servico
      bigquery_type: int64
      description: Quantidade de Policiais Militares mortos em confronto ou por lesão
          não natural fora de serviço
      temporal_coverage:
          - (1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false

number_rows: 163

metadata_modified:
