
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-me-rais

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Relação Anual de Informações Sociais (RAIS)

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization:
    - br-me

# Descrição do conjunto
notes: A Relação Anual de Informações Sociais (RAIS) é um relatório de informações socioeconômicas solicitado pela Secretaria de Trabalho do Ministério da Economia brasileiro às pessoas jurídicas e outros empregadores anualmente. Foi instituída pelo Decreto nº 76.900, de 23 de dezembro de 1975.

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - economia

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - emprego
    - empresa
    - firma
    - salario
    - trabalho

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: '2022-09-12T22:53:30.354205'
